name: ZAP Testing Demo
on:
  push:
    branches:
      - main
     
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: ZAP full Scan      
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          cmd_options: '-n "Context.context" -U "test" --hook "hook.py"'
          
#       - name: ZAP Baseline Scan      
#         uses: zaproxy/action-baseline@v0.5.0
#         with:
#           docker_name: 'owasp/zap2docker-stable'
#           target: 'http://testphp.vulnweb.com/'
#           cmd_options: '-n "Context.context" -U "test" --hook "hook.py"'
